name: Build and deploy LogControlDemo WinForms Desktop application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0
        
    - name: Build executable
      run: dotnet build --configuration Release --output ./release
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-directory
        path: .\release\
        overwrite: true

